[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9"

colored = "2"
chrono = "=0.4.39"

log = "0.4"
env_logger = "0.11"

serde = { version = "1.0", features = ["derive"] }